---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    
    # rhel:
      # hosts:
        # rhel_host:
        #   ansible_host: 192.168.1.100
        #   ansible_user: admin
